use_frameworks!

platform :ios, '8.0'

target 'ZGSpecialKit_Category_Example' do
  pod 'ZGSpecialKit_Category', :path => '../'

  target 'ZGSpecialKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
